In [1]:
import requests
import json
import pandas as pd
import numpy as np
from pprint import pprint as pp

In [2]:
generations = pd.read_json("API_datasets/gen.json")
regions = pd.read_json("API_datasets/region.json")

items = pd.read_json("API_datasets/item.json")
items_attr = pd.read_json("API_datasets/item_attr.json")
items_cat = pd.read_json("API_datasets/item_categ.json")

moves = pd.read_json("API_datasets/moves.json")
move_ail = pd.read_json("API_datasets/move_ail.json")
move_categ = pd.read_json("API_datasets/move_categ.json")
move_class = pd.read_json("API_datasets/move_class.json")
move_target = pd.read_json("API_datasets/move_target.json")

pkmn = pd.read_json("API_datasets/pokemon.json")
species = pd.read_json("API_datasets/species.json")
nature = pd.read_json("API_datasets/nature.json")
abilities = pd.read_json("API_datasets/abilities.json")
stats = pd.read_json("API_datasets/stat.json")
types = pd.read_json("API_datasets/types.json")

In [3]:
gen_df = pd.DataFrame(generations, columns=["id", "main_region", "moves", "name", "pokemon_species", "types"])
region_df = pd.DataFrame(regions, columns=["id", "locations", "main_generation", "name"])

items_df = pd.DataFrame(items, columns=["attributes", "category", "effect_entries", "id", "name"])
item_attributes_df = pd.DataFrame(items_attr, columns=["descriptions", "id", "items", "name"])
item_categories_df = pd.DataFrame(items_cat, columns=["id", "items", "name"])

moves_df = pd.DataFrame(moves, columns=["accuracy", "damage_class", "generation", "id", "learned_by_pokemon", "name", 
                                             "power", "pp", "type"])
move_ailments_df = pd.DataFrame(move_ail, columns=["id", "moves", "name"])
move_category_df = pd.DataFrame(move_categ, columns=["descriptions", "id", "moves", "name"])
move_class_df = pd.DataFrame(move_class, columns=["descriptions", "id", "moves", "name"])
move_target_df = pd.DataFrame(move_target, columns=["descriptions", "id", "moves", "name"])

pkmn_df = pd.DataFrame(pkmn, columns=["game_indices", "height", "id", "moves", "name", "weight"])
species_df = pd.DataFrame(species, columns=["evolves_from_species", "generation", "has_gender_differences", "id", 
                                                   "is_baby", "is_legendary", "is_mythical", "name", "varieties"])
ability_df = pd.DataFrame(abilities, columns=["effect_changes", "effect_entries", "generation", "id", "is_main_series", 
                                                   "name", "pokemon"])
nature_df = pd.DataFrame(nature, columns=["decreased_stat", "id", "increased_stat", "name"])
stat_df = pd.DataFrame(stats, columns=["affecting_moves", "affecting_natures", "id", "move_damage_class", "name"])
type_df = pd.DataFrame(types, columns=["damage_relations", "game_indices", "generation", "id", "name"])

In [4]:
gen_df = gen_df[["id", "name", "main_region", "pokemon_species", "moves", "types"]]
gen_df.columns = ["ID", "Gen_number", "Region_name", "New_pokemon", "New_moves", "New_types"]
region_df = region_df[["id", "name", "main_generation", "locations"]]
region_df.columns = ["ID", "Region_name", "Gen_number", "Locations"]

items_df = items_df[["id", "name", "attributes", "category", "effect_entries"]]
items_df.columns = ["ID", "Name", "Attributes", "Category", "Effect"]
item_attributes_df = item_attributes_df[["id", "name", "descriptions", "items"]]
item_attributes_df.columns = ["ID", "Name", "Descriptions", "Items"]
item_categories_df = item_categories_df[["id", "name", "items"]]
item_categories_df.columns = ["ID", "Name", "Items"]

moves_df = moves_df[["id", "name", "type", "power", "accuracy", "pp", "damage_class", "generation", "learned_by_pokemon"]]
moves_df.columns = ["ID", "Name", "Type", "Power", "Accuracy", "PP", "Damage_class", "Introducted_in", "Learned_by"]
move_ailments_df = move_ailments_df[["id", "name", "moves"]]
move_ailments_df.columns = ["ID", "Name", "Moves"]
move_category_df = move_category_df[["id", "name", "descriptions", "moves"]]
move_category_df.columns = ["ID", "Name", "Descriptions", "Moves"]
move_class_df = move_class_df[["id", "name", "descriptions", "moves"]]
move_class_df.columns = ["ID", "Name", "Descriptions", "Moves"]
move_target_df = move_target_df[["id", "name", "descriptions", "moves"]]
move_target_df.columns = ["ID", "Name", "Descriptions", "Moves"]

pkmn_df = pkmn_df[["id", "game_indices", "name", "moves", "height", "weight"]]
pkmn_df.columns = ["ID", "Game_index", "Name", "Moves", "Height", "Weight"]
species_df = species_df[["id", "name", "varieties", "generation", "evolves_from_species", "has_gender_differences",  "is_baby", 
                         "is_legendary", "is_mythical"]]
species_df.columns = ["ID", "Name", "Varieties", "Generation", "Evolves_from", "Has_gender_diff", "Is_baby", "Is_legendary",
                     "Is_mythical"]
ability_df = ability_df[["id", "name", "generation", "is_main_series", "effect_changes", "effect_entries", "pokemon"]]
ability_df.columns = ["ID", "Name", "Generation", "Is_Main_Series", "Effect_changes", "Effect_entries", "Pokemon"]
nature_df = nature_df[["id", "name", "decreased_stat", "increased_stat"]]
nature_df.columns = ["ID", "Name", "Decreased_stat", "Increased_stat"]
stat_df = stat_df[["id", "name", "affecting_moves", "affecting_natures", "move_damage_class"]]
stat_df.columns = ["ID", "Name", "Affecting_moves", "Affecting_natures", "Move_damage_class"]
type_df = type_df[["id", "game_indices", "name", "generation", "damage_relations"]]
type_df.columns = ["ID", "Game_index", "Name", "Introducted_in", "Damage_relations"]

### Generations

In [5]:
gen_df

,ID,Gen_number,Region_name,New_pokemon,New_moves,New_types
0,1,generation-i,"{'name': 'kanto', 'url': 'https://pokeapi.co/a...","[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'name': 'pound', 'url': 'https://pokeapi.co/...","[{'name': 'normal', 'url': 'https://pokeapi.co..."
1,2,generation-ii,"{'name': 'johto', 'url': 'https://pokeapi.co/a...","[{'name': 'chikorita', 'url': 'https://pokeapi...","[{'name': 'sketch', 'url': 'https://pokeapi.co...","[{'name': 'steel', 'url': 'https://pokeapi.co/..."
2,3,generation-iii,"{'name': 'hoenn', 'url': 'https://pokeapi.co/a...","[{'name': 'treecko', 'url': 'https://pokeapi.c...","[{'name': 'fake-out', 'url': 'https://pokeapi....","[{'name': 'shadow', 'url': 'https://pokeapi.co..."
3,4,generation-iv,"{'name': 'sinnoh', 'url': 'https://pokeapi.co/...","[{'name': 'turtwig', 'url': 'https://pokeapi.c...","[{'name': 'roost', 'url': 'https://pokeapi.co/...",[]
4,5,generation-v,"{'name': 'unova', 'url': 'https://pokeapi.co/a...","[{'name': 'victini', 'url': 'https://pokeapi.c...","[{'name': 'hone-claws', 'url': 'https://pokeap...",[]
5,6,generation-vi,"{'name': 'kalos', 'url': 'https://pokeapi.co/a...","[{'name': 'chespin', 'url': 'https://pokeapi.c...","[{'name': 'flying-press', 'url': 'https://poke...","[{'name': 'fairy', 'url': 'https://pokeapi.co/..."
6,7,generation-vii,"{'name': 'alola', 'url': 'https://pokeapi.co/a...","[{'name': 'rowlet', 'url': 'https://pokeapi.co...","[{'name': 'breakneck-blitz--physical', 'url': ...",[]
7,8,generation-viii,"{'name': 'galar', 'url': 'https://pokeapi.co/a...","[{'name': 'grookey', 'url': 'https://pokeapi.c...","[{'name': 'max-guard', 'url': 'https://pokeapi...",[]

In [6]:
#Replace Gen_number with an integer
gen_df['Gen_number'] = gen_df['ID']

In [7]:
#Extract just the name from 'Region_name' lists
for i in (gen_df['ID'].values):
    gen_df.loc[i-1, 'Region_name'] = gen_df[gen_df['ID'] == i]['Region_name'][i-1]['name']

In [8]:
gen_df.Region_name = gen_df.Region_name.str.capitalize()

In [9]:
gen_df

,ID,Gen_number,Region_name,New_pokemon,New_moves,New_types
0,1,1,Kanto,"[{'name': 'bulbasaur', 'url': 'https://pokeapi...","[{'name': 'pound', 'url': 'https://pokeapi.co/...","[{'name': 'normal', 'url': 'https://pokeapi.co..."
1,2,2,Johto,"[{'name': 'chikorita', 'url': 'https://pokeapi...","[{'name': 'sketch', 'url': 'https://pokeapi.co...","[{'name': 'steel', 'url': 'https://pokeapi.co/..."
2,3,3,Hoenn,"[{'name': 'treecko', 'url': 'https://pokeapi.c...","[{'name': 'fake-out', 'url': 'https://pokeapi....","[{'name': 'shadow', 'url': 'https://pokeapi.co..."
3,4,4,Sinnoh,"[{'name': 'turtwig', 'url': 'https://pokeapi.c...","[{'name': 'roost', 'url': 'https://pokeapi.co/...",[]
4,5,5,Unova,"[{'name': 'victini', 'url': 'https://pokeapi.c...","[{'name': 'hone-claws', 'url': 'https://pokeap...",[]
5,6,6,Kalos,"[{'name': 'chespin', 'url': 'https://pokeapi.c...","[{'name': 'flying-press', 'url': 'https://poke...","[{'name': 'fairy', 'url': 'https://pokeapi.co/..."
6,7,7,Alola,"[{'name': 'rowlet', 'url': 'https://pokeapi.co...","[{'name': 'breakneck-blitz--physical', 'url': ...",[]
7,8,8,Galar,"[{'name': 'grookey', 'url': 'https://pokeapi.c...","[{'name': 'max-guard', 'url': 'https://pokeapi...",[]

### Regions

In [10]:
region_df

,ID,Region_name,Gen_number,Locations
0,1,kanto,"{'name': 'generation-i', 'url': 'https://pokea...","[{'name': 'celadon-city', 'url': 'https://poke..."
1,2,johto,"{'name': 'generation-ii', 'url': 'https://poke...","[{'name': 'blackthorn-city', 'url': 'https://p..."
2,3,hoenn,"{'name': 'generation-iii', 'url': 'https://pok...","[{'name': 'petalburg-city', 'url': 'https://po..."
3,4,sinnoh,"{'name': 'generation-iv', 'url': 'https://poke...","[{'name': 'canalave-city', 'url': 'https://pok..."
4,5,unova,"{'name': 'generation-v', 'url': 'https://pokea...","[{'name': 'unova-mystery-zone', 'url': 'https:..."
5,6,kalos,"{'name': 'generation-vi', 'url': 'https://poke...","[{'name': 'vaniville-town', 'url': 'https://po..."
6,7,alola,"{'name': 'generation-vii', 'url': 'https://pok...","[{'name': 'alola-route-1--hauoli-outskirts', '..."
7,8,galar,"{'name': 'generation-viii', 'url': 'https://po...",[]

In [11]:
#Replace Gen_number with an integer
region_df['Gen_number'] = region_df['ID']

#Capitalize 'Region_name'
region_df.Region_name = region_df.Region_name.str.capitalize()

In [12]:
region_df

,ID,Region_name,Gen_number,Locations
0,1,Kanto,1,"[{'name': 'celadon-city', 'url': 'https://poke..."
1,2,Johto,2,"[{'name': 'blackthorn-city', 'url': 'https://p..."
2,3,Hoenn,3,"[{'name': 'petalburg-city', 'url': 'https://po..."
3,4,Sinnoh,4,"[{'name': 'canalave-city', 'url': 'https://pok..."
4,5,Unova,5,"[{'name': 'unova-mystery-zone', 'url': 'https:..."
5,6,Kalos,6,"[{'name': 'vaniville-town', 'url': 'https://po..."
6,7,Alola,7,"[{'name': 'alola-route-1--hauoli-outskirts', '..."
7,8,Galar,8,[]

### Items

In [13]:
#Capitalize names
items_df.Name = items_df.Name.str.capitalize()
items_df.tail()

,ID,Name,Attributes,Category,Effect
1602,1654,Shaderoot-carrot,[],"{'name': 'plot-advancement', 'url': 'https://p...",[]
1603,1655,Dynite-ore,[],"{'name': 'collectibles', 'url': 'https://pokea...",[]
1604,1656,Carrot-seeds,[],"{'name': 'plot-advancement', 'url': 'https://p...",[]
1605,1657,Ability-patch,[],"{'name': 'vitamins', 'url': 'https://pokeapi.c...",[]
1606,1658,Reins-of-unity,[],"{'name': 'plot-advancement', 'url': 'https://p...",[]

In [14]:
#Ci sono degli ID mancanti nella colonna ID (per via di quelli skippati dalla API nell'ottenimento dei dati).
#Vado a resettare la colonna, da 1 a 1607 come dovrebbe essere
for i in range(0, items_df.shape[0]):
    items_df.loc[i, 'ID'] = i+1
    
items_df.tail()

,ID,Name,Attributes,Category,Effect
1602,1603,Shaderoot-carrot,[],"{'name': 'plot-advancement', 'url': 'https://p...",[]
1603,1604,Dynite-ore,[],"{'name': 'collectibles', 'url': 'https://pokea...",[]
1604,1605,Carrot-seeds,[],"{'name': 'plot-advancement', 'url': 'https://p...",[]
1605,1606,Ability-patch,[],"{'name': 'vitamins', 'url': 'https://pokeapi.c...",[]
1606,1607,Reins-of-unity,[],"{'name': 'plot-advancement', 'url': 'https://p...",[]

In [15]:
#I mantain just the short effect in the Effect attribute
for i in (items_df['ID'].values):
    try:
        items_df.loc[i-1, 'Effect'] = items_df[items_df['ID'] == i]['Effect'][i-1][0]['short_effect']
    except IndexError:
        items_df.loc[i-1, 'Effect'] = np.NaN

In [16]:
items_df.tail()

,ID,Name,Attributes,Category,Effect
1602,1603,Shaderoot-carrot,[],"{'name': 'plot-advancement', 'url': 'https://p...",NaN
1603,1604,Dynite-ore,[],"{'name': 'collectibles', 'url': 'https://pokea...",NaN
1604,1605,Carrot-seeds,[],"{'name': 'plot-advancement', 'url': 'https://p...",NaN
1605,1606,Ability-patch,[],"{'name': 'vitamins', 'url': 'https://pokeapi.c...",NaN
1606,1607,Reins-of-unity,[],"{'name': 'plot-advancement', 'url': 'https://p...",NaN

In [17]:
items_df[items_df['Effect'].notnull()]

,ID,Name,Attributes,Category,Effect
0,1,Master-ball,"[{'name': 'countable', 'url': 'https://pokeapi...","{'name': 'standard-balls', 'url': 'https://pok...",Catches a wild Pokémon every time.
1,2,Ultra-ball,"[{'name': 'countable', 'url': 'https://pokeapi...","{'name': 'standard-balls', 'url': 'https://pok...",Tries to catch a wild Pokémon. Success rate i...
2,3,Great-ball,"[{'name': 'countable', 'url': 'https://pokeapi...","{'name': 'standard-balls', 'url': 'https://pok...",Tries to catch a wild Pokémon. Success rate i...
3,4,Poke-ball,"[{'name': 'countable', 'url': 'https://pokeapi...","{'name': 'standard-balls', 'url': 'https://pok...",Tries to catch a wild Pokémon.
4,5,Safari-ball,"[{'name': 'countable', 'url': 'https://pokeapi...","{'name': 'standard-balls', 'url': 'https://pok...",Tries to catch a wild Pokémon in the Great Mar...
...,...,...,...,...,...
949,950,Roto-stealth,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",XXX new effect for roto-stealth
950,951,Roto-hp-restore,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",XXX new effect for roto-hp-restore
951,952,Roto-pp-restore,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",XXX new effect for roto-pp-restore
952,953,Roto-boost,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",XXX new effect for roto-boost
953,954,Roto-catch,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",XXX new effect for roto-catch

In [18]:
items_df[items_df['Effect'].isnull()]

,ID,Name,Attributes,Category,Effect
954,955,Autograph,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",NaN
955,956,Pokemon-box,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",NaN
956,957,Medicine-pocket,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",NaN
957,958,Candy-jar,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",NaN
958,959,Power-up-pocket,[],"{'name': 'unused', 'url': 'https://pokeapi.co/...",NaN
...,...,...,...,...,...
1602,1603,Shaderoot-carrot,[],"{'name': 'plot-advancement', 'url': 'https://p...",NaN
1603,1604,Dynite-ore,[],"{'name': 'collectibles', 'url': 'https://pokea...",NaN
1604,1605,Carrot-seeds,[],"{'name': 'plot-advancement', 'url': 'https://p...",NaN
1605,1606,Ability-patch,[],"{'name': 'vitamins', 'url': 'https://pokeapi.c...",NaN
1606,1607,Reins-of-unity,[],"{'name': 'plot-advancement', 'url': 'https://p...",NaN

I primi 954 strumenti hanno l'effetto, i successivi no.

In [19]:
#Stessa cosa per la categoria, mantengo solo il nome
for i in (items_df['ID'].values):
        items_df.loc[i-1, 'Category'] = items_df[items_df['ID'] == i]['Category'][i-1]['name']

In [20]:
items_df.Category = items_df.Category.str.capitalize()
items_df.head()

,ID,Name,Attributes,Category,Effect
0,1,Master-ball,"[{'name': 'countable', 'url': 'https://pokeapi...",Standard-balls,Catches a wild Pokémon every time.
1,2,Ultra-ball,"[{'name': 'countable', 'url': 'https://pokeapi...",Standard-balls,Tries to catch a wild Pokémon. Success rate i...
2,3,Great-ball,"[{'name': 'countable', 'url': 'https://pokeapi...",Standard-balls,Tries to catch a wild Pokémon. Success rate i...
3,4,Poke-ball,"[{'name': 'countable', 'url': 'https://pokeapi...",Standard-balls,Tries to catch a wild Pokémon.
4,5,Safari-ball,"[{'name': 'countable', 'url': 'https://pokeapi...",Standard-balls,Tries to catch a wild Pokémon in the Great Mar...

In [21]:
for i in (items_df['ID'].values):
    temp = []
    for j in range(0, len(items_df[items_df['ID'] == i]['Attributes'][i-1])):
        temp.append(items_df[items_df['ID'] == i]['Attributes'][i-1][j]['name'])
    #In questo caso uso .at perchè .loc da problemi con l'assegnamento delle liste
    items_df.at[i-1, 'Attributes'] = temp

In [22]:
items_df.head()

,ID,Name,Attributes,Category,Effect
0,1,Master-ball,"[countable, consumable, usable-in-battle, hold...",Standard-balls,Catches a wild Pokémon every time.
1,2,Ultra-ball,"[countable, consumable, usable-in-battle, hold...",Standard-balls,Tries to catch a wild Pokémon. Success rate i...
2,3,Great-ball,"[countable, consumable, usable-in-battle, hold...",Standard-balls,Tries to catch a wild Pokémon. Success rate i...
3,4,Poke-ball,"[countable, consumable, usable-in-battle, hold...",Standard-balls,Tries to catch a wild Pokémon.
4,5,Safari-ball,"[countable, consumable, usable-in-battle, hold...",Standard-balls,Tries to catch a wild Pokémon in the Great Mar...

In [23]:
#Salvataggio sia in .csv che in .json
items_df.to_json("API_datasets\DATASET PER INTEGRAZIONE\items.json.gz", orient='records', lines=True, compression='gzip')
items_df.to_csv("API_datasets\DATASET PER INTEGRAZIONE\items.csv")

### Item attributes

In [24]:
item_attributes_df.Name = item_attributes_df.Name.str.capitalize()
item_attributes_df

,ID,Name,Descriptions,Items
0,1,Countable,"[{'description': 'Has a count in the bag', 'la...","[{'name': 'master-ball', 'url': 'https://pokea..."
1,2,Consumable,"[{'description': 'Consumed when used', 'langua...","[{'name': 'master-ball', 'url': 'https://pokea..."
2,3,Usable-overworld,"[{'description': 'Usable outside battle', 'lan...","[{'name': 'potion', 'url': 'https://pokeapi.co..."
3,4,Usable-in-battle,"[{'description': 'Usable in battle', 'language...","[{'name': 'master-ball', 'url': 'https://pokea..."
4,5,Holdable,"[{'description': 'Can be held by a Pokémon', '...","[{'name': 'master-ball', 'url': 'https://pokea..."
5,6,Holdable-passive,"[{'description': 'Works passively when held', ...",[]
6,7,Holdable-active,[{'description': 'Usable by a Pokémon when hel...,"[{'name': 'cheri-berry', 'url': 'https://pokea..."
7,8,Underground,[{'description': 'Appears in Sinnoh Undergroun...,"[{'name': 'revive', 'url': 'https://pokeapi.co..."

In [25]:
#Extract just the description from 'Descriptions' lists
for i in (item_attributes_df['ID'].values):
    item_attributes_df.loc[i-1, 'Descriptions'] = item_attributes_df[item_attributes_df['ID'] == i]['Descriptions'][i-1][0]['description']

In [26]:
item_attributes_df

,ID,Name,Descriptions,Items
0,1,Countable,Has a count in the bag,"[{'name': 'master-ball', 'url': 'https://pokea..."
1,2,Consumable,Consumed when used,"[{'name': 'master-ball', 'url': 'https://pokea..."
2,3,Usable-overworld,Usable outside battle,"[{'name': 'potion', 'url': 'https://pokeapi.co..."
3,4,Usable-in-battle,Usable in battle,"[{'name': 'master-ball', 'url': 'https://pokea..."
4,5,Holdable,Can be held by a Pokémon,"[{'name': 'master-ball', 'url': 'https://pokea..."
5,6,Holdable-passive,Works passively when held,[]
6,7,Holdable-active,Usable by a Pokémon when held,"[{'name': 'cheri-berry', 'url': 'https://pokea..."
7,8,Underground,Appears in Sinnoh Underground,"[{'name': 'revive', 'url': 'https://pokeapi.co..."

### Item categories

In [27]:
item_categories_df.Name = item_categories_df.Name.str.capitalize()
item_categories_df.head()

   ID         Name                                              Items
0   1  Stat-boosts  [{'name': 'guard-spec', 'url': 'https://pokeap...
1   2  Effort-drop  [{'name': 'pomeg-berry', 'url': 'https://pokea...
2   3     Medicine  [{'name': 'cheri-berry', 'url': 'https://pokea...
3   4        Other  [{'name': 'enigma-berry', 'url': 'https://poke...
4   5   In-a-pinch  [{'name': 'liechi-berry', 'url': 'https://poke...

### Moves

In [28]:
moves_df.Name = moves_df.Name.str.capitalize()
moves_df.tail()

,ID,Name,Type,Power,Accuracy,PP,Damage_class,Introducted_in,Learned_by
839,10014,Shadow-hold,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,NaN,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
840,10015,Shadow-mist,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,100.0,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
841,10016,Shadow-panic,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,90.0,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
842,10017,Shadow-shed,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,NaN,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
843,10018,Shadow-sky,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,NaN,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]

In [29]:
#Ci sono degli ID mancanti nella colonna ID (per via di quelli skippati dalla API nell'ottenimento dei dati)
for i in range(0, moves_df.shape[0]):
    moves_df.loc[i, 'ID'] = i+1
    
moves_df.tail()

,ID,Name,Type,Power,Accuracy,PP,Damage_class,Introducted_in,Learned_by
839,840,Shadow-hold,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,NaN,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
840,841,Shadow-mist,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,100.0,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
841,842,Shadow-panic,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,90.0,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
842,843,Shadow-shed,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,NaN,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]
843,844,Shadow-sky,"{'name': 'shadow', 'url': 'https://pokeapi.co/...",NaN,NaN,NaN,"{'name': 'status', 'url': 'https://pokeapi.co/...","{'name': 'generation-iii', 'url': 'https://pok...",[]

In [30]:
#Extract just the type from 'Type' lists, damage class from 'Damage_class' lists and generation from 'Introducted_in' lists
for i in (moves_df['ID'].values):
    moves_df.loc[i-1, 'Type'] = moves_df[moves_df['ID'] == i]['Type'][i-1]['name']
    moves_df.loc[i-1, 'Damage_class'] = moves_df[moves_df['ID'] == i]['Damage_class'][i-1]['name']
    moves_df.loc[i-1, 'Introducted_in'] = moves_df[moves_df['ID'] == i]['Introducted_in'][i-1]['name']

In [31]:
moves_df.Type = moves_df.Type.str.capitalize()
moves_df.Damage_class = moves_df.Damage_class.str.capitalize()
moves_df.head()

,ID,Name,Type,Power,Accuracy,PP,Damage_class,Introducted_in,Learned_by
0,1,Pound,Normal,40.0,100.0,35.0,Physical,generation-i,"[{'name': 'clefairy', 'url': 'https://pokeapi...."
1,2,Karate-chop,Fighting,50.0,100.0,25.0,Physical,generation-i,"[{'name': 'mankey', 'url': 'https://pokeapi.co..."
2,3,Double-slap,Normal,15.0,85.0,10.0,Physical,generation-i,"[{'name': 'clefairy', 'url': 'https://pokeapi...."
3,4,Comet-punch,Normal,18.0,85.0,15.0,Physical,generation-i,"[{'name': 'hitmonchan', 'url': 'https://pokeap..."
4,5,Mega-punch,Normal,80.0,85.0,20.0,Physical,generation-i,"[{'name': 'charmander', 'url': 'https://pokeap..."

In [32]:
for index, row in moves_df.iterrows():
    if row['Introducted_in'] == 'generation-i':
        moves_df.loc[index,'Introducted_in'] = '1'
    elif row['Introducted_in'] == 'generation-ii':
        moves_df.loc[index,'Introducted_in'] = '2'
    elif row['Introducted_in'] == 'generation-iii':
        moves_df.loc[index,'Introducted_in'] = '3'
    elif row['Introducted_in'] == 'generation-iv':
        moves_df.loc[index,'Introducted_in'] = '4'
    elif row['Introducted_in'] == 'generation-v':
        moves_df.loc[index,'Introducted_in'] = '5'
    elif row['Introducted_in'] == 'generation-vi':
        moves_df.loc[index,'Introducted_in'] = '6'
    elif row['Introducted_in'] == 'generation-vii':
        moves_df.loc[index,'Introducted_in'] = '7'
    elif row['Introducted_in'] == 'generation-viii':
        moves_df.loc[index,'Introducted_in'] = '8'

In [33]:
moves_df.head()

,ID,Name,Type,Power,Accuracy,PP,Damage_class,Introducted_in,Learned_by
0,1,Pound,Normal,40.0,100.0,35.0,Physical,1,"[{'name': 'clefairy', 'url': 'https://pokeapi...."
1,2,Karate-chop,Fighting,50.0,100.0,25.0,Physical,1,"[{'name': 'mankey', 'url': 'https://pokeapi.co..."
2,3,Double-slap,Normal,15.0,85.0,10.0,Physical,1,"[{'name': 'clefairy', 'url': 'https://pokeapi...."
3,4,Comet-punch,Normal,18.0,85.0,15.0,Physical,1,"[{'name': 'hitmonchan', 'url': 'https://pokeap..."
4,5,Mega-punch,Normal,80.0,85.0,20.0,Physical,1,"[{'name': 'charmander', 'url': 'https://pokeap..."

In [34]:
moves_df.tail()

,ID,Name,Type,Power,Accuracy,PP,Damage_class,Introducted_in,Learned_by
839,840,Shadow-hold,Shadow,NaN,NaN,NaN,Status,3,[]
840,841,Shadow-mist,Shadow,NaN,100.0,NaN,Status,3,[]
841,842,Shadow-panic,Shadow,NaN,90.0,NaN,Status,3,[]
842,843,Shadow-shed,Shadow,NaN,NaN,NaN,Status,3,[]
843,844,Shadow-sky,Shadow,NaN,NaN,NaN,Status,3,[]

In [35]:
#Salvataggio sia in .csv che in .json
moves_df.to_json("API_datasets\DATASET PER INTEGRAZIONE\moves.json.gz", orient='records', lines=True, compression='gzip')
moves_df.to_csv("API_datasets\DATASET PER INTEGRAZIONE\moves.csv")

### Move ailments

In [36]:
move_ailments_df.head()

   ID       Name                                              Moves
0  -1    unknown  [{'name': 'tri-attack', 'url': 'https://pokeap...
1   0       none  [{'name': 'pound', 'url': 'https://pokeapi.co/...
2   1  paralysis  [{'name': 'thunder-punch', 'url': 'https://pok...
3   2      sleep  [{'name': 'sing', 'url': 'https://pokeapi.co/a...
4   3     freeze  [{'name': 'ice-punch', 'url': 'https://pokeapi...

In [37]:
#Resetto gli ID che partono da -1
for i in range(0, move_ailments_df.shape[0]):
    move_ailments_df.loc[i, 'ID'] = i+1
    
move_ailments_df.head()

   ID       Name                                              Moves
0   1    unknown  [{'name': 'tri-attack', 'url': 'https://pokeap...
1   2       none  [{'name': 'pound', 'url': 'https://pokeapi.co/...
2   3  paralysis  [{'name': 'thunder-punch', 'url': 'https://pok...
3   4      sleep  [{'name': 'sing', 'url': 'https://pokeapi.co/a...
4   5     freeze  [{'name': 'ice-punch', 'url': 'https://pokeapi...

In [38]:
move_ailments_df.Name = move_ailments_df.Name.str.capitalize()
move_ailments_df.head()

   ID       Name                                              Moves
0   1    Unknown  [{'name': 'tri-attack', 'url': 'https://pokeap...
1   2       None  [{'name': 'pound', 'url': 'https://pokeapi.co/...
2   3  Paralysis  [{'name': 'thunder-punch', 'url': 'https://pok...
3   4      Sleep  [{'name': 'sing', 'url': 'https://pokeapi.co/a...
4   5     Freeze  [{'name': 'ice-punch', 'url': 'https://pokeapi...

### Move categories

In [39]:
move_category_df.Name = move_category_df.Name.str.capitalize()
move_category_df.head()

,ID,Name,Descriptions,Moves
0,0,Damage,"[{'description': 'Inflicts damage', 'language'...","[{'name': 'pound', 'url': 'https://pokeapi.co/..."
1,1,Ailment,[{'description': 'No damage; inflicts status a...,"[{'name': 'sing', 'url': 'https://pokeapi.co/a..."
2,2,Net-good-stats,[{'description': 'No damage; lowers target's s...,"[{'name': 'swords-dance', 'url': 'https://poke..."
3,3,Heal,"[{'description': 'No damage; heals the user', ...","[{'name': 'recover', 'url': 'https://pokeapi.c..."
4,4,Damage+ailment,[{'description': 'Inflicts damage; inflicts st...,"[{'name': 'fire-punch', 'url': 'https://pokeap..."

In [40]:
#Resetto gli ID
for i in range(0, move_category_df.shape[0]):
    move_category_df.loc[i, 'ID'] = i+1
    
move_category_df.head()

,ID,Name,Descriptions,Moves
0,1,Damage,"[{'description': 'Inflicts damage', 'language'...","[{'name': 'pound', 'url': 'https://pokeapi.co/..."
1,2,Ailment,[{'description': 'No damage; inflicts status a...,"[{'name': 'sing', 'url': 'https://pokeapi.co/a..."
2,3,Net-good-stats,[{'description': 'No damage; lowers target's s...,"[{'name': 'swords-dance', 'url': 'https://poke..."
3,4,Heal,"[{'description': 'No damage; heals the user', ...","[{'name': 'recover', 'url': 'https://pokeapi.c..."
4,5,Damage+ailment,[{'description': 'Inflicts damage; inflicts st...,"[{'name': 'fire-punch', 'url': 'https://pokeap..."

In [41]:
#Extract just the description from 'Descriptions' lists
for i in (move_category_df['ID'].values):
    move_category_df.loc[i-1, 'Descriptions'] = move_category_df[move_category_df['ID'] == i]['Descriptions'][i-1][0]['description']

In [42]:
move_category_df.head()

,ID,Name,Descriptions,Moves
0,1,Damage,Inflicts damage,"[{'name': 'pound', 'url': 'https://pokeapi.co/..."
1,2,Ailment,No damage; inflicts status ailment,"[{'name': 'sing', 'url': 'https://pokeapi.co/a..."
2,3,Net-good-stats,No damage; lowers target's stats or raises use...,"[{'name': 'swords-dance', 'url': 'https://poke..."
3,4,Heal,No damage; heals the user,"[{'name': 'recover', 'url': 'https://pokeapi.c..."
4,5,Damage+ailment,Inflicts damage; inflicts status ailment,"[{'name': 'fire-punch', 'url': 'https://pokeap..."

### Move classes

In [43]:
move_class_df.Name = move_class_df.Name.str.capitalize()
move_class_df.head()

,ID,Name,Descriptions,Moves
0,1,Status,"[{'description': 'ダメージない', 'language': {'name'...","[{'name': 'swords-dance', 'url': 'https://poke..."
1,2,Physical,"[{'description': 'ぶつりのダメージ。こうげきとぼうぎょを行使する', 'l...","[{'name': 'pound', 'url': 'https://pokeapi.co/..."
2,3,Special,"[{'description': 'とくしゅのダメージ。とくこうととくぼうを行使する', '...","[{'name': 'razor-wind', 'url': 'https://pokeap..."

In [44]:
#Tengo solo la descrizione in inglese. Essendo solo 3 dati conviene semplicemente trascrivere a mano la descrizione:
for i in range (0,3):
    print(move_class_df['Descriptions'][i][4])

{'description': 'No damage', 'language': {'name': 'en', 'url': 'https://pokeapi.co/api/v2/language/9/'}}
{'description': 'Physical damage, controlled by Attack and Defense', 'language': {'name': 'en', 'url': 'https://pokeapi.co/api/v2/language/9/'}}
{'description': 'Special damage, controlled by Special Attack and Special Defense', 'language': {'name': 'en', 'url': 'https://pokeapi.co/api/v2/language/9/'}}

In [45]:
#La descrizione per 'status' è 'No damage'
move_class_df.loc[0,'Descriptions'] = 'No damage'

#La descrizione per 'physical' è 'Physical damage, controlled by Attack and Defense'
move_class_df.loc[1,'Descriptions'] = 'Physical damage, controlled by Attack and Defense'

#La descrizione per 'physical' è 'Special damage, controlled by Special Attack and Special Defense'
move_class_df.loc[2,'Descriptions'] = 'Special damage, controlled by Special Attack and Special Defense'

move_class_df

,ID,Name,Descriptions,Moves
0,1,Status,No damage,"[{'name': 'swords-dance', 'url': 'https://poke..."
1,2,Physical,"Physical damage, controlled by Attack and Defense","[{'name': 'pound', 'url': 'https://pokeapi.co/..."
2,3,Special,"Special damage, controlled by Special Attack a...","[{'name': 'razor-wind', 'url': 'https://pokeap..."

### Move targets

In [46]:
move_target_df.Name = move_target_df.Name.str.capitalize()
move_target_df

,ID,Name,Descriptions,Moves
0,1,Specific-move,[{'description': 'Eine spezifische Fähigkeit. ...,"[{'name': 'counter', 'url': 'https://pokeapi.c..."
1,2,Selected-pokemon-me-first,[{'description': 'Ein anderes vom Trainer ausg...,"[{'name': 'me-first', 'url': 'https://pokeapi...."
2,3,Ally,[{'description': 'Die Partner des Anwenders (w...,"[{'name': 'helping-hand', 'url': 'https://poke..."
3,4,Users-field,[{'description': 'Die Seite des Anwenders auf ...,"[{'name': 'mist', 'url': 'https://pokeapi.co/a..."
4,5,User-or-ally,[{'description': 'Entweder der Anwender oder s...,"[{'name': 'acupressure', 'url': 'https://pokea..."
5,6,Opponents-field,[{'description': 'Die andere Seite des Feldes....,"[{'name': 'spikes', 'url': 'https://pokeapi.co..."
6,7,User,"[{'description': 'Der Anwender.', 'language': ...","[{'name': 'swords-dance', 'url': 'https://poke..."
7,8,Random-opponent,[{'description': 'Ein zufälliges gegnerische P...,"[{'name': 'thrash', 'url': 'https://pokeapi.co..."
8,9,All-other-pokemon,[{'description': 'Jedes andere Pokémon auf dem...,"[{'name': 'surf', 'url': 'https://pokeapi.co/a..."
9,10,Selected-pokemon,[{'description': 'Ein anderes Pokémon auf dem ...,"[{'name': 'pound', 'url': 'https://pokeapi.co/..."
10,11,All-opponents,"[{'description': 'Alle gegnerischen Pokémon.',...","[{'name': 'razor-wind', 'url': 'https://pokeap..."
11,12,Entire-field,[{'description': 'Das komplette Feld. Betriff...,"[{'name': 'haze', 'url': 'https://pokeapi.co/a..."
12,13,User-and-allies,[{'description': 'Der Anwender und seine Partn...,"[{'name': 'heal-bell', 'url': 'https://pokeapi..."
13,14,All-pokemon,[{'description': 'Jedes Pokémon auf dem Feld.'...,"[{'name': 'perish-song', 'url': 'https://pokea..."
14,15,All-allies,"[{'description': 'All of the user's allies.', ...",[]

In [47]:
#Vale per tutte le prime 14 righe
move_target_df['Descriptions'][0][1]

{'description': 'One specific move.  How this move is chosen depends upon on the move being used.',
 'language': {'name': 'en', 'url': 'https://pokeapi.co/api/v2/language/9/'}}

In [48]:
#Ultima riga
move_target_df['Descriptions'][14][0]

{'description': "All of the user's allies.",
 'language': {'name': 'en', 'url': 'https://pokeapi.co/api/v2/language/9/'}}

In [49]:
#Tutte le righe della descrizione hanno la descrizione in tedesco al primo posto e in inglese al secondo, eccezion fatta per
#l'ultima riga che ha solo la descrizione in inglese

for i in (move_target_df['ID'].values):
    if i <= 14:
        move_target_df.loc[i-1, 'Descriptions'] = move_target_df[move_target_df['ID'] == i]['Descriptions'][i-1][1]['description']
    else:
        move_target_df.loc[i-1, 'Descriptions'] = move_target_df[move_target_df['ID'] == i]['Descriptions'][i-1][0]['description']

In [50]:
move_target_df

,ID,Name,Descriptions,Moves
0,1,Specific-move,One specific move. How this move is chosen de...,"[{'name': 'counter', 'url': 'https://pokeapi.c..."
1,2,Selected-pokemon-me-first,"One other Pokémon on the field, selected by th...","[{'name': 'me-first', 'url': 'https://pokeapi...."
2,3,Ally,The user's ally (if any).,"[{'name': 'helping-hand', 'url': 'https://poke..."
3,4,Users-field,The user's side of the field. Affects the use...,"[{'name': 'mist', 'url': 'https://pokeapi.co/a..."
4,5,User-or-ally,"Either the user or its ally, selected by the t...","[{'name': 'acupressure', 'url': 'https://pokea..."
5,6,Opponents-field,The opposing side of the field. Affects oppos...,"[{'name': 'spikes', 'url': 'https://pokeapi.co..."
6,7,User,The user.,"[{'name': 'swords-dance', 'url': 'https://poke..."
7,8,Random-opponent,"One opposing Pokémon, selected at random.","[{'name': 'thrash', 'url': 'https://pokeapi.co..."
8,9,All-other-pokemon,Every other Pokémon on the field.,"[{'name': 'surf', 'url': 'https://pokeapi.co/a..."
9,10,Selected-pokemon,"One other Pokémon on the field, selected by th...","[{'name': 'pound', 'url': 'https://pokeapi.co/..."
10,11,All-opponents,All opposing Pokémon.,"[{'name': 'razor-wind', 'url': 'https://pokeap..."
11,12,Entire-field,The entire field. Affects all Pokémon.,"[{'name': 'haze', 'url': 'https://pokeapi.co/a..."
12,13,User-and-allies,The user and its allies.,"[{'name': 'heal-bell', 'url': 'https://pokeapi..."
13,14,All-pokemon,Every Pokémon on the field.,"[{'name': 'perish-song', 'url': 'https://pokea..."
14,15,All-allies,All of the user's allies.,[]

### Pokemon

In [51]:
#Questo dataframe contiene tutte le versioni dei vari pokemon, comprese le varianti speciali
pkmn_df.Name = pkmn_df.Name.str.capitalize()
pkmn_df.drop('Game_index', axis=1, inplace=True)
pkmn_df.head()

,ID,Name,Moves,Height,Weight
0,1,Bulbasaur,"[{'move': {'name': 'razor-wind', 'url': 'https...",7,69
1,2,Ivysaur,"[{'move': {'name': 'swords-dance', 'url': 'htt...",10,130
2,3,Venusaur,"[{'move': {'name': 'swords-dance', 'url': 'htt...",20,1000
3,4,Charmander,"[{'move': {'name': 'mega-punch', 'url': 'https...",6,85
4,5,Charmeleon,"[{'move': {'name': 'mega-punch', 'url': 'https...",11,190

In [52]:
#Salvataggio sia in .csv che in .json
pkmn_df.to_json("API_datasets\DATASET PER INTEGRAZIONE\pokemon.json.gz", orient='records', lines=True, compression='gzip')
pkmn_df.to_csv("API_datasets\DATASET PER INTEGRAZIONE\pokemon.csv")

### Species

In [53]:
#Questo dataframe contiene una riga per ciascuna specie, nella colonna 'Varieties' sono presenti le varie forme alternative
#Tengo la colonna 'Varieties' così com'è, la considero una relazione
species_df.Name = species_df.Name.str.capitalize()
species_df.head()

,ID,Name,Varieties,Generation,Evolves_from,Has_gender_diff,Is_baby,Is_legendary,Is_mythical
0,1,Bulbasaur,"[{'is_default': True, 'pokemon': {'name': 'bul...","{'name': 'generation-i', 'url': 'https://pokea...",None,False,False,False,False
1,2,Ivysaur,"[{'is_default': True, 'pokemon': {'name': 'ivy...","{'name': 'generation-i', 'url': 'https://pokea...","{'name': 'bulbasaur', 'url': 'https://pokeapi....",False,False,False,False
2,3,Venusaur,"[{'is_default': True, 'pokemon': {'name': 'ven...","{'name': 'generation-i', 'url': 'https://pokea...","{'name': 'ivysaur', 'url': 'https://pokeapi.co...",True,False,False,False
3,4,Charmander,"[{'is_default': True, 'pokemon': {'name': 'cha...","{'name': 'generation-i', 'url': 'https://pokea...",None,False,False,False,False
4,5,Charmeleon,"[{'is_default': True, 'pokemon': {'name': 'cha...","{'name': 'generation-i', 'url': 'https://pokea...","{'name': 'charmander', 'url': 'https://pokeapi...",False,False,False,False

In [54]:
#Extract just the generation from 'Generation' lists 
for i in (species_df['ID'].values):
    species_df.loc[i-1, 'Generation'] = species_df[species_df['ID'] == i]['Generation'][i-1]['name']

In [55]:
species_df.head()

,ID,Name,Varieties,Generation,Evolves_from,Has_gender_diff,Is_baby,Is_legendary,Is_mythical
0,1,Bulbasaur,"[{'is_default': True, 'pokemon': {'name': 'bul...",generation-i,None,False,False,False,False
1,2,Ivysaur,"[{'is_default': True, 'pokemon': {'name': 'ivy...",generation-i,"{'name': 'bulbasaur', 'url': 'https://pokeapi....",False,False,False,False
2,3,Venusaur,"[{'is_default': True, 'pokemon': {'name': 'ven...",generation-i,"{'name': 'ivysaur', 'url': 'https://pokeapi.co...",True,False,False,False
3,4,Charmander,"[{'is_default': True, 'pokemon': {'name': 'cha...",generation-i,None,False,False,False,False
4,5,Charmeleon,"[{'is_default': True, 'pokemon': {'name': 'cha...",generation-i,"{'name': 'charmander', 'url': 'https://pokeapi...",False,False,False,False

In [56]:
#Extract just the name from 'Evolves_from' lists 
for i in (species_df['ID'].values):
    try:
        species_df.loc[i-1, 'Evolves_from'] = species_df[species_df['ID'] == i]['Evolves_from'][i-1]['name']
    except TypeError:
        species_df.loc[i-1, 'Evolves_from'] = np.NaN

In [57]:
species_df.Evolves_from = species_df.Evolves_from.str.capitalize()
species_df.head()

,ID,Name,Varieties,Generation,Evolves_from,Has_gender_diff,Is_baby,Is_legendary,Is_mythical
0,1,Bulbasaur,"[{'is_default': True, 'pokemon': {'name': 'bul...",generation-i,NaN,False,False,False,False
1,2,Ivysaur,"[{'is_default': True, 'pokemon': {'name': 'ivy...",generation-i,Bulbasaur,False,False,False,False
2,3,Venusaur,"[{'is_default': True, 'pokemon': {'name': 'ven...",generation-i,Ivysaur,True,False,False,False
3,4,Charmander,"[{'is_default': True, 'pokemon': {'name': 'cha...",generation-i,NaN,False,False,False,False
4,5,Charmeleon,"[{'is_default': True, 'pokemon': {'name': 'cha...",generation-i,Charmander,False,False,False,False

In [58]:
#Aggiungo una colonna che riassume le colonne 'Is_baby', 'Is_legendary' e 'Is_mythical' (se tutte sono false li chiamo 'Common')
for index, row in species_df.iterrows():
    if row['Is_baby'] == True:
        species_df.loc[index,'Rarity'] = 'Baby'
    elif row['Is_legendary'] == True:
        species_df.loc[index,'Rarity'] = 'Legendary'
    elif row['Is_mythical'] == True:
        species_df.loc[index,'Rarity'] = 'Mythical'
    else:
        species_df.loc[index,'Rarity'] = 'Common'

In [59]:
species_df.drop(['Is_baby', 'Is_legendary', 'Is_mythical'], axis=1, inplace=True)
species_df.tail(15)

,ID,Name,Varieties,Generation,Evolves_from,Has_gender_diff,Rarity
883,884,Duraludon,"[{'is_default': True, 'pokemon': {'name': 'dur...",generation-viii,NaN,False,Common
884,885,Dreepy,"[{'is_default': True, 'pokemon': {'name': 'dre...",generation-viii,NaN,False,Common
885,886,Drakloak,"[{'is_default': True, 'pokemon': {'name': 'dra...",generation-viii,Dreepy,False,Common
886,887,Dragapult,"[{'is_default': True, 'pokemon': {'name': 'dra...",generation-viii,Drakloak,False,Common
887,888,Zacian,"[{'is_default': True, 'pokemon': {'name': 'zac...",generation-viii,NaN,False,Legendary
888,889,Zamazenta,"[{'is_default': True, 'pokemon': {'name': 'zam...",generation-viii,NaN,False,Legendary
889,890,Eternatus,"[{'is_default': True, 'pokemon': {'name': 'ete...",generation-viii,NaN,False,Legendary
890,891,Kubfu,"[{'is_default': True, 'pokemon': {'name': 'kub...",generation-viii,NaN,False,Legendary
891,892,Urshifu,"[{'is_default': True, 'pokemon': {'name': 'urs...",generation-viii,Kubfu,False,Legendary
892,893,Zarude,"[{'is_default': True, 'pokemon': {'name': 'zar...",generation-viii,NaN,False,Mythical
893,894,Regieleki,"[{'is_default': True, 'pokemon': {'name': 'reg...",generation-viii,NaN,False,Legendary
894,895,Regidrago,"[{'is_default': True, 'pokemon': {'name': 'reg...",generation-viii,NaN,False,Legendary
895,896,Glastrier,"[{'is_default': True, 'pokemon': {'name': 'gla...",generation-viii,NaN,False,Legendary
896,897,Spectrier,"[{'is_default': True, 'pokemon': {'name': 'spe...",generation-viii,NaN,False,Legendary
897,898,Calyrex,"[{'is_default': True, 'pokemon': {'name': 'cal...",generation-viii,NaN,False,Legendary

In [60]:
for index, row in species_df.iterrows():
    if row['Generation'] == 'generation-i':
        species_df.loc[index,'Generation'] = '1'
    elif row['Generation'] == 'generation-ii':
        species_df.loc[index,'Generation'] = '2'
    elif row['Generation'] == 'generation-iii':
        species_df.loc[index,'Generation'] = '3'
    elif row['Generation'] == 'generation-iv':
        species_df.loc[index,'Generation'] = '4'
    elif row['Generation'] == 'generation-v':
        species_df.loc[index,'Generation'] = '5'
    elif row['Generation'] == 'generation-vi':
        species_df.loc[index,'Generation'] = '6'
    elif row['Generation'] == 'generation-vii':
        species_df.loc[index,'Generation'] = '7'
    elif row['Generation'] == 'generation-viii':
        species_df.loc[index,'Generation'] = '8'

In [61]:
species_df.head()

,ID,Name,Varieties,Generation,Evolves_from,Has_gender_diff,Rarity
0,1,Bulbasaur,"[{'is_default': True, 'pokemon': {'name': 'bul...",1,NaN,False,Common
1,2,Ivysaur,"[{'is_default': True, 'pokemon': {'name': 'ivy...",1,Bulbasaur,False,Common
2,3,Venusaur,"[{'is_default': True, 'pokemon': {'name': 'ven...",1,Ivysaur,True,Common
3,4,Charmander,"[{'is_default': True, 'pokemon': {'name': 'cha...",1,NaN,False,Common
4,5,Charmeleon,"[{'is_default': True, 'pokemon': {'name': 'cha...",1,Charmander,False,Common

In [62]:
species_df.tail()

,ID,Name,Varieties,Generation,Evolves_from,Has_gender_diff,Rarity
893,894,Regieleki,"[{'is_default': True, 'pokemon': {'name': 'reg...",8,NaN,False,Legendary
894,895,Regidrago,"[{'is_default': True, 'pokemon': {'name': 'reg...",8,NaN,False,Legendary
895,896,Glastrier,"[{'is_default': True, 'pokemon': {'name': 'gla...",8,NaN,False,Legendary
896,897,Spectrier,"[{'is_default': True, 'pokemon': {'name': 'spe...",8,NaN,False,Legendary
897,898,Calyrex,"[{'is_default': True, 'pokemon': {'name': 'cal...",8,NaN,False,Legendary

In [64]:
#Salvataggio sia in .csv che in .json
species_df.to_json("API_datasets\DATASET PER INTEGRAZIONE\species.json.gz", orient='records', lines=True, compression='gzip')
species_df.to_csv("API_datasets\DATASET PER INTEGRAZIONE\species.csv")

### Abilities

In [65]:
ability_df.Name = ability_df.Name.str.capitalize()

#Resetto gli IDs
for i in range(0, ability_df.shape[0]):
    ability_df.loc[i, 'ID'] = i+1
    
ability_df.tail()

,ID,Name,Generation,Is_Main_Series,Effect_changes,Effect_entries,Pokemon
322,323,Run-up,"{'name': 'generation-v', 'url': 'https://pokea...",False,[],[],[]
323,324,Conqueror,"{'name': 'generation-v', 'url': 'https://pokea...",False,[],[],[]
324,325,Shackle,"{'name': 'generation-v', 'url': 'https://pokea...",False,[],[],[]
325,326,Decoy,"{'name': 'generation-v', 'url': 'https://pokea...",False,[],[],[]
326,327,Shield,"{'name': 'generation-v', 'url': 'https://pokea...",False,[],[],[]

In [66]:
#Extract just the generation from 'Generation' lists 
for i in (ability_df['ID'].values):
    ability_df.loc[i-1, 'Generation'] = ability_df[ability_df['ID'] == i]['Generation'][i-1]['name']

In [67]:
ability_df.tail()

,ID,Name,Generation,Is_Main_Series,Effect_changes,Effect_entries,Pokemon
322,323,Run-up,generation-v,False,[],[],[]
323,324,Conqueror,generation-v,False,[],[],[]
324,325,Shackle,generation-v,False,[],[],[]
325,326,Decoy,generation-v,False,[],[],[]
326,327,Shield,generation-v,False,[],[],[]

In [68]:
#A noi interessano solo le abilità disponibili nei giochi della serie principale, quindi:
mainseries_ability_df = ability_df[ability_df['Is_Main_Series'] == True]
mainseries_ability_df.tail()

,ID,Name,Generation,Is_Main_Series,Effect_changes,Effect_entries,Pokemon
262,263,Dragons-maw,generation-viii,True,[],[],"[{'is_hidden': False, 'pokemon': {'name': 'reg..."
263,264,Chilling-neigh,generation-viii,True,[],[],"[{'is_hidden': False, 'pokemon': {'name': 'gla..."
264,265,Grim-neigh,generation-viii,True,[],[],"[{'is_hidden': False, 'pokemon': {'name': 'spe..."
265,266,As-one-glastrier,generation-viii,True,[],[],"[{'is_hidden': False, 'pokemon': {'name': 'cal..."
266,267,As-one-spectrier,generation-viii,True,[],[],"[{'is_hidden': False, 'pokemon': {'name': 'cal..."

La colonna 'Effect_changes' contiene i cambiamenti degli effetti dell'abilità col passare delle versioni. Lascio la colonna per sicurezza, anche se a noi interesse l'effetto attuale, che è contenuto nella colonna 'Effect_entries'. Ha senso comunque fare integrazione coi dati dello scraping.

In [69]:
#Fino all'abilità con ID=191 abbiamo sia la descrizione in tedesco che in inglese. Dall' ID=192 fino alla fine abbiamo solo la 
#descrizione in inglese

for i in (mainseries_ability_df['ID'].values):
    try:
        if i <= 191:
            mainseries_ability_df.loc[i-1, 'Effect_entries'] = mainseries_ability_df[mainseries_ability_df['ID'] == i]['Effect_entries'][i-1][1]['effect']
        else:
            mainseries_ability_df.loc[i-1, 'Effect_entries'] = mainseries_ability_df[mainseries_ability_df['ID'] == i]['Effect_entries'][i-1][0]['effect']
    except IndexError:
        mainseries_ability_df.loc[i-1, 'Effect_entries'] = np.NaN

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [70]:
mainseries_ability_df.head()

,ID,Name,Generation,Is_Main_Series,Effect_changes,Effect_entries,Pokemon
0,1,Stench,generation-iii,True,[{'effect_entries': [{'effect': 'Hat im Kampf ...,This Pokémon's damaging moves have a 10% chanc...,"[{'is_hidden': True, 'pokemon': {'name': 'gloo..."
1,2,Drizzle,generation-iii,True,[],The weather changes to rain when this Pokémon ...,"[{'is_hidden': True, 'pokemon': {'name': 'poli..."
2,3,Speed-boost,generation-iii,True,[],This Pokémon's Speed rises one stage after eac...,"[{'is_hidden': False, 'pokemon': {'name': 'yan..."
3,4,Battle-armor,generation-iii,True,[],Moves cannot score critical hits against this ...,"[{'is_hidden': True, 'pokemon': {'name': 'cubo..."
4,5,Sturdy,generation-iii,True,[{'effect_entries': [{'effect': 'Verhindert ke...,"When this Pokémon is at full HP, any hit that ...","[{'is_hidden': False, 'pokemon': {'name': 'geo..."

In [71]:
for index, row in mainseries_ability_df.iterrows():
    if row['Generation'] == 'generation-i':
        mainseries_ability_df.loc[index,'Generation'] = '1'
    elif row['Generation'] == 'generation-ii':
        mainseries_ability_df.loc[index,'Generation'] = '2'
    elif row['Generation'] == 'generation-iii':
        mainseries_ability_df.loc[index,'Generation'] = '3'
    elif row['Generation'] == 'generation-iv':
        mainseries_ability_df.loc[index,'Generation'] = '4'
    elif row['Generation'] == 'generation-v':
        mainseries_ability_df.loc[index,'Generation'] = '5'
    elif row['Generation'] == 'generation-vi':
        mainseries_ability_df.loc[index,'Generation'] = '6'
    elif row['Generation'] == 'generation-vii':
        mainseries_ability_df.loc[index,'Generation'] = '7'
    elif row['Generation'] == 'generation-viii':
        mainseries_ability_df.loc[index,'Generation'] = '8'

C:\ProgramData\Anaconda3\lib\site-packages\pandas\core\indexing.py:1817: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self._setitem_single_column(loc, value, pi)

In [72]:
mainseries_ability_df.head()

,ID,Name,Generation,Is_Main_Series,Effect_changes,Effect_entries,Pokemon
0,1,Stench,3,True,[{'effect_entries': [{'effect': 'Hat im Kampf ...,This Pokémon's damaging moves have a 10% chanc...,"[{'is_hidden': True, 'pokemon': {'name': 'gloo..."
1,2,Drizzle,3,True,[],The weather changes to rain when this Pokémon ...,"[{'is_hidden': True, 'pokemon': {'name': 'poli..."
2,3,Speed-boost,3,True,[],This Pokémon's Speed rises one stage after eac...,"[{'is_hidden': False, 'pokemon': {'name': 'yan..."
3,4,Battle-armor,3,True,[],Moves cannot score critical hits against this ...,"[{'is_hidden': True, 'pokemon': {'name': 'cubo..."
4,5,Sturdy,3,True,[{'effect_entries': [{'effect': 'Verhindert ke...,"When this Pokémon is at full HP, any hit that ...","[{'is_hidden': False, 'pokemon': {'name': 'geo..."

In [73]:
mainseries_ability_df.tail()

,ID,Name,Generation,Is_Main_Series,Effect_changes,Effect_entries,Pokemon
262,263,Dragons-maw,8,True,[],NaN,"[{'is_hidden': False, 'pokemon': {'name': 'reg..."
263,264,Chilling-neigh,8,True,[],NaN,"[{'is_hidden': False, 'pokemon': {'name': 'gla..."
264,265,Grim-neigh,8,True,[],NaN,"[{'is_hidden': False, 'pokemon': {'name': 'spe..."
265,266,As-one-glastrier,8,True,[],NaN,"[{'is_hidden': False, 'pokemon': {'name': 'cal..."
266,267,As-one-spectrier,8,True,[],NaN,"[{'is_hidden': False, 'pokemon': {'name': 'cal..."

In [74]:
#Salvataggio sia in .csv che in .json
mainseries_ability_df.to_json("API_datasets\DATASET PER INTEGRAZIONE\Abilities.json.gz", orient='records', lines=True, compression='gzip')
mainseries_ability_df.to_csv("API_datasets\DATASET PER INTEGRAZIONE\Abilities.csv")

### Natures

In [75]:
nature_df.Name = nature_df.Name.str.capitalize()
nature_df.tail()

,ID,Name,Decreased_stat,Increased_stat
20,21,Brave,"{'name': 'speed', 'url': 'https://pokeapi.co/a...","{'name': 'attack', 'url': 'https://pokeapi.co/..."
21,22,Relaxed,"{'name': 'speed', 'url': 'https://pokeapi.co/a...","{'name': 'defense', 'url': 'https://pokeapi.co..."
22,23,Quiet,"{'name': 'speed', 'url': 'https://pokeapi.co/a...","{'name': 'special-attack', 'url': 'https://pok..."
23,24,Sassy,"{'name': 'speed', 'url': 'https://pokeapi.co/a...","{'name': 'special-defense', 'url': 'https://po..."
24,25,Serious,None,None

In [76]:
for i in (nature_df['ID'].values):
    try:
        nature_df.loc[i-1, 'Decreased_stat'] = nature_df[nature_df['ID'] == i]['Decreased_stat'][i-1]['name']
        nature_df.loc[i-1, 'Increased_stat'] = nature_df[nature_df['ID'] == i]['Increased_stat'][i-1]['name']
    except TypeError:
        nature_df.loc[i-1, 'Decreased_stat'] = np.NaN
        nature_df.loc[i-1, 'Increased_stat'] = np.NaN

In [77]:
nature_df.Decreased_stat = nature_df.Decreased_stat.str.capitalize()
nature_df.Increased_stat = nature_df.Increased_stat.str.capitalize()
nature_df

    ID     Name   Decreased_stat   Increased_stat
0    1    Hardy              NaN              NaN
1    2     Bold           Attack          Defense
2    3   Modest           Attack   Special-attack
3    4     Calm           Attack  Special-defense
4    5    Timid           Attack            Speed
5    6   Lonely          Defense           Attack
6    7   Docile              NaN              NaN
7    8     Mild          Defense   Special-attack
8    9   Gentle          Defense  Special-defense
9   10    Hasty          Defense            Speed
10  11  Adamant   Special-attack           Attack
11  12   Impish   Special-attack          Defense
12  13  Bashful              NaN              NaN
13  14  Careful   Special-attack  Special-defense
14  15     Rash  Special-defense   Special-attack
15  16    Jolly   Special-attack            Speed
16  17  Naughty  Special-defense           Attack
17  18      Lax  Special-defense          Defense
18  19   Quirky              NaN              NaN
19  20    Naive  Special-defense            Speed
20  21    Brave            Speed           Attack
21  22  Relaxed            Speed          Defense
22  23    Quiet            Speed   Special-attack
23  24    Sassy            Speed  Special-defense
24  25  Serious              NaN              NaN

### Stats

In [78]:
stat_df.Name = stat_df.Name.str.capitalize()
stat_df

,ID,Name,Affecting_moves,Affecting_natures,Move_damage_class
0,1,Hp,"{'decrease': [], 'increase': []}","{'decrease': [], 'increase': []}",None
1,2,Attack,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'bold', 'url': 'https:/...","{'name': 'physical', 'url': 'https://pokeapi.c..."
2,3,Defense,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'lonely', 'url': 'https...","{'name': 'physical', 'url': 'https://pokeapi.c..."
3,4,Special-attack,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'adamant', 'url': 'http...","{'name': 'special', 'url': 'https://pokeapi.co..."
4,5,Special-defense,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'rash', 'url': 'https:/...","{'name': 'special', 'url': 'https://pokeapi.co..."
5,6,Speed,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'brave', 'url': 'https:...",None
6,7,Accuracy,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [], 'increase': []}",None
7,8,Evasion,"{'decrease': [{'change': -2, 'move': {'name': ...","{'decrease': [], 'increase': []}",None

In [79]:
for i in (stat_df['ID'].values):
    try:
        stat_df.loc[i-1, 'Move_damage_class'] = stat_df[stat_df['ID'] == i]['Move_damage_class'][i-1]['name']
    except TypeError:
        stat_df.loc[i-1, 'Move_damage_class'] = np.NaN

In [80]:
stat_df.Move_damage_class = stat_df.Move_damage_class.str.capitalize()
stat_df

,ID,Name,Affecting_moves,Affecting_natures,Move_damage_class
0,1,Hp,"{'decrease': [], 'increase': []}","{'decrease': [], 'increase': []}",NaN
1,2,Attack,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'bold', 'url': 'https:/...",Physical
2,3,Defense,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'lonely', 'url': 'https...",Physical
3,4,Special-attack,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'adamant', 'url': 'http...",Special
4,5,Special-defense,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'rash', 'url': 'https:/...",Special
5,6,Speed,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [{'name': 'brave', 'url': 'https:...",NaN
6,7,Accuracy,"{'decrease': [{'change': -1, 'move': {'name': ...","{'decrease': [], 'increase': []}",NaN
7,8,Evasion,"{'decrease': [{'change': -2, 'move': {'name': ...","{'decrease': [], 'increase': []}",NaN

### Types

In [81]:
type_df.Name = type_df.Name.str.capitalize()

#Resetto gli indici
for i in range(0, type_df.shape[0]):
    type_df.loc[i, 'ID'] = i+1
    
type_df.tail()

,ID,Game_index,Name,Introducted_in,Damage_relations
15,16,"[{'game_index': 26, 'generation': {'name': 'ge...",Dragon,"{'name': 'generation-i', 'url': 'https://pokea...","{'double_damage_from': [{'name': 'ice', 'url':..."
16,17,"[{'game_index': 27, 'generation': {'name': 'ge...",Dark,"{'name': 'generation-ii', 'url': 'https://poke...","{'double_damage_from': [{'name': 'fighting', '..."
17,18,"[{'game_index': 17, 'generation': {'name': 'ge...",Fairy,"{'name': 'generation-vi', 'url': 'https://poke...","{'double_damage_from': [{'name': 'poison', 'ur..."
18,19,"[{'game_index': 19, 'generation': {'name': 'ge...",Unknown,"{'name': 'generation-ii', 'url': 'https://poke...","{'double_damage_from': [], 'double_damage_to':..."
19,20,[],Shadow,"{'name': 'generation-iii', 'url': 'https://pok...","{'double_damage_from': [], 'double_damage_to':..."

In [82]:
#Extract just the generation from 'Generation' lists 
for i in (type_df['ID'].values):
    type_df.loc[i-1, 'Introducted_in'] = type_df[type_df['ID'] == i]['Introducted_in'][i-1]['name']
    
type_df.tail()

,ID,Game_index,Name,Introducted_in,Damage_relations
15,16,"[{'game_index': 26, 'generation': {'name': 'ge...",Dragon,generation-i,"{'double_damage_from': [{'name': 'ice', 'url':..."
16,17,"[{'game_index': 27, 'generation': {'name': 'ge...",Dark,generation-ii,"{'double_damage_from': [{'name': 'fighting', '..."
17,18,"[{'game_index': 17, 'generation': {'name': 'ge...",Fairy,generation-vi,"{'double_damage_from': [{'name': 'poison', 'ur..."
18,19,"[{'game_index': 19, 'generation': {'name': 'ge...",Unknown,generation-ii,"{'double_damage_from': [], 'double_damage_to':..."
19,20,[],Shadow,generation-iii,"{'double_damage_from': [], 'double_damage_to':..."

In [83]:
for index, row in type_df.iterrows():
    if row['Introducted_in'] == 'generation-i':
        type_df.loc[index,'Introducted_in'] = '1'
    elif row['Introducted_in'] == 'generation-ii':
        type_df.loc[index,'Introducted_in'] = '2'
    elif row['Introducted_in'] == 'generation-iii':
        type_df.loc[index,'Introducted_in'] = '3'
    elif row['Introducted_in'] == 'generation-iv':
        type_df.loc[index,'Introducted_in'] = '4'
    elif row['Introducted_in'] == 'generation-v':
        type_df.loc[index,'Introducted_in'] = '5'
    elif row['Introducted_in'] == 'generation-vi':
        type_df.loc[index,'Introducted_in'] = '6'
    elif row['Introducted_in'] == 'generation-vii':
        type_df.loc[index,'Introducted_in'] = '7'
    elif row['Introducted_in'] == 'generation-viii':
        type_df.loc[index,'Introducted_in'] = '8'

In [84]:
#Salvataggio sia in .csv che in .json
type_df.to_json("API_datasets\DATASET PER INTEGRAZIONE\Types.json.gz", orient='records', lines=True, compression='gzip')
type_df.to_csv("API_datasets\DATASET PER INTEGRAZIONE\Types.csv")